custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/const.py, custom_components/extended_openai_conversation/helpers.py
Function calls are deprecated, "tools" are now recommended. It's basically the same thing, but allows multiple tool calls in a single message.
This now changes the default function to take a single service as argument - preferring to split it into multiple separate tool calls instead. The old form is still supported for existing templates.
I've found tool calls have way less issues with repeating the same call multiple times. This may have been related to the messages previously not including the correct sequence of function_call, function output, but I didn't confirm (tool calls are more strict in requiring exact request -> response sequences).
Additionally, I've changed the output to handle additional validation errors, and return the error text to OpenAI.
I also ran into some cases …
=> Use tool_calls instead of functions

README.md, custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/config_flow.py, custom_components/extended_openai_conversation/const.py, custom_components/extended_openai_conversation/strings.json, custom_components/extended_openai_conversation/translations/en.json, custom_components/extended_openai_conversation/translations/ko.json
I wanted my assistant to know who it was talking to.
If there is a user_id attached to the context that is provided via `user_input`, retrieve the name of the user from HASS's authentication manager. This primarily applies when interacting with the UI or invoking the process service from a user context.
Add voice recognition to wake word detection to differentiate the user who started the conversation
Add voice recognition to differentiate the user who is currently speaking - allowing for multiple participate in a conversation
=> feat: Attach the user's name to the user message payload if known

examples/function/shopping_list/README.md
UpdateShopping list example with a better TODO example
Will allow adding and updating lists with completed checkmarks while referencing any todo entity. 
Still working on how to get it to see a response from the service call todo.get_items, the response contains an array of what is in the list we would need to parse through and either check so we dont create duplicates or if the question is asked, what is on my list?
=> UpdateShopping list example with a better TODO example

custom_components/extended_openai_conversation/__init__.py
- https://github.com/jekalmin/extended_openai_conversation/issues/49
- If OpenAIError occurs, the error message is not only responded but also logged.
=> [#49] add OpenAIError log

custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/config_flow.py, custom_components/extended_openai_conversation/const.py, custom_components/extended_openai_conversation/helpers.py, custom_components/extended_openai_conversation/strings.json, custom_components/extended_openai_conversation/translations/de.json, custom_components/extended_openai_conversation/translations/en.json, custom_components/extended_openai_conversation/translations/ko.json, custom_components/extended_openai_conversation/translations/nl.json
- #42
- support azure openai
- test needed (Since I don't have azure openai API, it is not tested yet)
=> [#42] add azure openai (test needed)

custom_components/extended_openai_conversation/__init__.py
- make `functions` optional
- By setting `Functions` to `[]` like below, it will not pass `functions` parameter to openai
=> [#57] make functions optional

examples/function/calendar/README.md
fixes #88 by removing a deprecated function call with the new call. Tested on my local installation.
=> removed deprecated function in calendar

custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/exceptions.py, custom_components/extended_openai_conversation/helpers.py
#86
- Add `area_id` and `device_id` to `execute_services` function
- One of following is required to call `execute_services`
- `entity_id`
- `area_id`
- `device_id`
``````yaml
Areas:
```yaml
{%- for area in areas() %}
- {{area}}
{%- endfor %}
```
``````
```yaml
- spec:
name: execute_services
description: Use this function to execute service of devices in Home Assistant.
parameters:
type: object
properties:
list:
type: array
items:
type: object
properties:
domain:
type: string
description: The domain of the service
service:
type: string
description: The service to be called
service_data:
type: object
description: The service data object to indicate what to control.
properties:
entity_id:
type: array
items:
type: string
description: The entity_id retrieved from available devices. It must …
```
=> [#86] "area_id" and "deviced_id" can be set to execute_service

custom_components/extended_openai_conversation/__init__.py
Area awareness feature in [Year of Voice Chapter 5](https://www.home-assistant.io/blog/2023/12/13/year-of-the-voice-chapter-5/#area-awareness) 
- Added "current_device_id" variable in prompt.
1. Assign area to your ESP-S3-BOX or Atom echo.
2. Copy and paste prompt below.
3. Ask "turn on light", "turn off light"
``````
I want you to act as smart home manager of Home Assistant.
I will provide information of smart home along with a question, you will truthfully make correction or answer using information provided in one sentence in everyday language.
Current Time: {{now()}}
Current Area: {{area_id(current_device_id)}}
Available Devices:
```csv
entity_id,name,state,area_id,aliases
{% for entity in exposed_entities -%}
{{ entity.entity_id }},{{ entity.name }},{{ entity.state …
```
=> Add area awareness

custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/const.py
- Enable users to track token usage, message history, etc...
- `data.response.usage.total_tokens`: Total tokens
- `data.messages`: Message history of current context
- `data.user_input.conversation_id`: Current context id
- `data.user_input.device_id`: Device id
```yaml
trigger:
- platform: event
event_type: extended_openai_conversation.conversation.finished
condition: []
action:
- service: input_number.set_value
target:
entity_id: input_number.YOUR_ENTITY_ID
data:
value: "{{trigger.event.data.response.usage.total_tokens}}"
```
```yaml
event_type: extended_openai_conversation.conversation.finished
data:
response:
id: chatcmpl-8l3km5sMmk3IhAgACol3zxEqZX9dy
choices:
- finish_reason: stop
index: 0
message:
content: The living room light has been turned on.
role: assistant
function_call: null …
```
=> [#105] fire "extended_openai_conversation.conversation.finished" event

custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/exceptions.py, custom_components/extended_openai_conversation/helpers.py, custom_components/extended_openai_conversation/manifest.json
- Get energy information
```yaml
- spec:
name: get_energy_statistic_ids
description: Get statistics
parameters:
type: object
properties:
dummy:
type: string
description: Nothing
function:
type: composite
sequence:
- type: native
name: get_energy
response_variable: result
- type: template
value_template: "{{result.device_consumption | map(attribute='stat_consumption') | list}}"
```
```yaml
- spec:
name: get_statistics
description: Get statistics
parameters:
type: object
properties:
start_time:
type: string
description: The start datetime
end_time:
type: string
description: The end datetime
statistic_ids:
type: array
items:
type: string
description: The statistic ids
period:
type: string
description: The period
enum:
- day
- week
- month
required:
- start_time
- end_time
- statistic_ids
- …
```
=> [#94] add energy, statistics function

custom_components/extended_openai_conversation/manifest.json, custom_components/extended_openai_conversation/services.py
- #140
- Make local image to be accessible in `extended_openai_conversation.query_image`.
=> [#140] Make local image to be attached in `query_image` service

custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/helpers.py, examples/function/user_id_to_user/README.md
I have the Voice over IP integration working with extended OpenAI Conversation, which allows me to VoIP connect into the voice assistant.  However, to make this work we need to pass an acceptable user.name to OpenAI which does not allow spaces.
Currently this is the error we receive:
Error code: 400 - {'error': {'message': "'Voice over IP' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
The attached patch converts spaces to underscores, and the VoIP integration now works well with this integration.
=> User user_id for user identification

examples/function/camera_image_query/README.md
This PR provides an example functions for:
1. generate a camera snapshot image.
2. use the query image service call to analyze the image and return a text description
3. A combined function that does 1 and 2 above.
All three functions tested.
The integration works well with 1 and 2 defined, and the LLM figures out how to combined them, so option 3 is only for those that want really want to combined them.
I recommend keeping filename exposed so that the LLM can manage it, and potentially delete it or overwrite it.
=> Function spec examples for camera and image query

examples/function/say_tts/README.md
A flexible say tts example.  This allows the LLM to pass in any tts entity so it can direct the message to where it is needed.
=> Function spec example for say_tts

examples/function/youtube/README.md
Hi,
Thanks for creating this quality integration! I've been having a lot of fun using it.
I followed the YouTube example to play on my Apple TV and ran into an error from an indentation typo in the script yaml.
I also noticed that the youtube urls were being double quoted in the execution trace of the script (though this did not result in an error):
> media_content_id: '"youtube://www.youtube.com/playlist?list=WL"'
This PR fixes both of those issues.
=> Fix example YouTube scripts

README.md
just copied the new example as calendar.list_events is deprecated.
=> Update README.md according to calendar example file

custom_components/extended_openai_conversation/__init__.py, custom_components/extended_openai_conversation/helpers.py
- #217
```
2024-10-27 13:45:53.213 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7bebd793ddd0>,) inside the event loop by custom integration 'extended_openai_conversation' at custom_components/extended_openai_conversation/helpers.py, line 146: client = AsyncOpenAI( (offender: /home/vscode/.local/ha-venv/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/jekalmin/extended_openai_conversation/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
```
- Fix blocking call to verify cafile.
=> [#217] resolve "blocking call" warning log.

README.md, custom_components/extended_openai_conversation/helpers.py
Changes to support Azure API Management as AI Gateway to balance, observe and protect Azure OpenAI resources.
=> Added Azure API Management Support

custom_components/extended_openai_conversation/__init__.py
This continues with function/tool calling even if finish_reason == "stop".
Details:
I am using litellm OpenAI proxy to connect to none OpenAI models with extended_openai_conversation. 
It is known that Google Gemini models respond with finish_reason=="stop" even if wanting to execute a tool or function. See [https://github.com/BerriAI/litellm/issues/2195](https://github.com/BerriAI/litellm/issues/2195) and [https://github.com/BerriAI/litellm/issues/6104](https://github.com/BerriAI/litellm/issues/6104) 
It appears more often with non-streaming. 
Here is a log showing example response that causes the problem. 
I tested and this happens with every Gemini model from 1.5 to latest 2.0 Flash.
``
2025-01-01 17:38:29.608 INFO (MainThread) [custom_components.extended_openai_conversation] Response …
=> Fix Google Gemini bug with finish_reason

custom_components/extended_openai_conversation/helpers.py
Update AZURE_DOMAIN_PATTERN to include services.ai.azure.com as a valid Azure API base URL. 
``` 
API_KEY=XXXXX
API_Base_URL=https://xxxxx.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview
API_VERSION=2024-05-01-preview
```
Tested on DeepSeek-R1 deployment on Azure AI Foundry.
=> Update AZURE_DOMAIN_PATTERN to accept other regex pattern
